package simyukkuri.gameobject.yukkuri.statistic.statistics

import messageutil.MessageCollection
import simyukkuri.gameobject.yukkuri.statistic.YukkuriStats
import simyukkuri.randomElement

/** メッセージを取り出すためのクラス. */
class MessagePicker(self: YukkuriStats, private val messageCollection: MessageCollection) {
    val findsFood: String? = messageCollection["findsFood"]?.get(self.messageCondition)?.randomElement()
    val wantsFood: String? = messageCollection["wantsFood"]?.get(self.messageCondition)?.randomElement()
    val sexuallyExcited: String? = messageCollection["sexuallyExcited"]?.get(self.messageCondition)?.randomElement()
    val relaxed: String? = messageCollection["relaxed"]?.get(self.messageCondition)?.randomElement()
    val furifuri: String? = messageCollection["furifuri"]?.get(self.messageCondition)?.randomElement()
    val wakesUp: String? = messageCollection["wakesUp"]?.get(self.messageCondition)?.randomElement()
    val sleeping: String? = messageCollection["sleeping"]?.get(self.messageCondition)?.randomElement()
    val screams: String? = messageCollection["screams"]?.get(self.messageCondition)?.randomElement()
    val scared: String? = messageCollection["scared"]?.get(self.messageCondition)?.randomElement()
    val scaredAtRaper: String? = messageCollection["scaredAtRaper"]?.get(self.messageCondition)?.randomElement()
    val alarmed: String? = messageCollection["alarmed"]?.get(self.messageCondition)?.randomElement()
    val killedInstantly: String? = messageCollection["killedInstantly"]?.get(self.messageCondition)?.randomElement()
    val dies: String? = messageCollection["dies"]?.get(self.messageCondition)?.randomElement()
    val eating: String? = messageCollection["eating"]?.get(self.messageCondition)?.randomElement()
    val eatingPoo: String? = messageCollection["eatingPoo"]?.get(self.messageCondition)?.randomElement()
    val hasEatenBitter: String? = messageCollection["hasEatenBitter"]?.get(self.messageCondition)?.randomElement()
    val getsFull: String? = messageCollection["getsFull"]?.get(self.messageCondition)?.randomElement()
    val takesSweets: String? = messageCollection["takesSweets"]?.get(self.messageCondition)?.randomElement()
    val hasSukkiried: String? = messageCollection["hasSukkiried"]?.get(self.messageCondition)?.randomElement()
    val born: String? = messageCollection["born"]?.get(self.messageCondition)?.randomElement()
    val startsToPoop: String? = messageCollection["startsToPoop"]?.get(self.messageCondition)?.randomElement()
    val needsToPoop: String? = messageCollection["needsToPoop"]?.get(self.messageCondition)?.randomElement()
    val hasPooped: String? = messageCollection["hasPooped"]?.get(self.messageCondition)?.randomElement()
    val leaksPoo: String? = messageCollection["leaksPoo"]?.get(self.messageCondition)?.randomElement()
    val surisuri: String? = messageCollection["surisuri"]?.get(self.messageCondition)?.randomElement()
    val peropero: String? = messageCollection["peropero"]?.get(self.messageCondition)?.randomElement()
    val bearing: String? = messageCollection["bearing"]?.get(self.messageCondition)?.randomElement()
    val lamentsForAbortingBaby: String? = messageCollection["lamentsForAbortingBaby"]?.get(self.messageCondition)?.randomElement()
    val complainsAboutPoo: String? = messageCollection["complainsAboutPoo"]?.get(self.messageCondition)?.randomElement()
    val hungry: String? = messageCollection["hungry"]?.get(self.messageCondition)?.randomElement()
    val losesOkazari: String? = messageCollection["losesOkazari"]?.get(self.messageCondition)?.randomElement()
    val despisesYukkuriHavingNoOkazari: String? = messageCollection["despisesYukkuriHavingNoOkazari"]?.get(self.messageCondition)?.randomElement()
    val saysLikeFlying: String? = messageCollection["saysLikeFlying"]?.get(self.messageCondition)?.randomElement()
    val childDies: String? = messageCollection["childDies"]?.get(self.messageCondition)?.randomElement()
    val partnerDies: String? = messageCollection["partnerDies"]?.get(self.messageCondition)?.randomElement()
    val elderSisterDies: String? = messageCollection["elderSisterDies"]?.get(self.messageCondition)?.randomElement()
    val youngerSisterDies: String? = messageCollection["youngerSisterDies"]?.get(self.messageCondition)?.randomElement()
    val blockedByWall: String? = messageCollection["blockedByWall"]?.get(self.messageCondition)?.randomElement()
    val getsTreasure: String? = messageCollection["getsTreasure"]?.get(self.messageCondition)?.randomElement()
    val treasureTaken: String? = messageCollection["treasureTaken"]?.get(self.messageCondition)?.randomElement()
    val nobinobi: String? = messageCollection["nobinobi"]?.get(self.messageCondition)?.randomElement()
}